[package]
name = "rawdog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", default-features = false }
clap = { version = "4.5.20", features = ["derive", "env", "string", "unicode"] }
phf = { version = "0.11.2", features = ["macros"] }
rawler = "0.6.0"
zips = "0.1.7"
