name: Rust

on:
  push:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always


jobs:
  checks:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    name: Checks

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy -- -Dwarnings

  test:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    needs: checks
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runs tests
        run: cargo test

  build:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    name: Build
    needs: checks

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build [development]
        run: cargo build --verbose

      - name: Build [release]
        run: cargo build --verbose --release
